Style/ClassVars:
  # Default
  # Enabled: true
  Enabled: false

Style/Documentation:
  # Default
  # Enabled: true
  Enabled: false

Metrics/AbcSize:
  # Default
  # Max: 15
  Max: 34

Metrics/ClassLength:
  # Default
  # Max: 100
  Max: 171

Metrics/CyclomaticComplexity:
  # Default
  # Max: 6
  Max: 9

Metrics/LineLength:
  # Default
  # Max: 80
  Max: 103

Metrics/MethodLength:
  # Default
  # Max: 10
  Max: 19
